CREATE TABLE large_table (
    id BIGINT PRIMARY KEY,
    col1 INT,
    col2 VARCHAR(50),
    col3 VARCHAR(50),
    col4 DECIMAL(18,2),
    col5 DATETIME2,
    col6 BIT,
    col7 FLOAT,
    col8 NVARCHAR(100),
    col9 INT
);
GO

INSERT INTO large_table
SELECT TOP (50000000)
    ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS id,
    (ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 1000) AS col1,
    'value_' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(20)) AS col2,
    'name_' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(20)) AS col3,
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS DECIMAL(18,2)) / 100 AS col4,
    DATEADD(DAY, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 365, '2020-01-01') AS col5,
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 2 AS BIT) AS col6,
    CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS FLOAT) AS col7,
    'desc_' + CAST(ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS VARCHAR(20)) AS col8,
    (ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) % 100000) AS col9
FROM (SELECT 1 AS n FROM sys.all_objects a CROSS JOIN sys.all_objects b CROSS JOIN sys.all_objects c CROSS JOIN sys.all_objects d) t;
GO

SELECT COUNT(*) AS total_rows FROM large_table;
GO